### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by gati** [Data4Democracy/datafordemocracy.org#1]
- Our mission
- short history
- a list of projects people can get involved with (with links to project detail page)
- Information about how to get in contact and join the group
- our technology partners (like data.world and Domino Data Labs)

**Comment by geckya** [comment]
A couple things to consider wrt how to get in contact and join the group:
* do we want to start using slackit (or something?) for invites?
* should we add a contact form, or just "contact us" info for orgs looking for nerd powered help?

**Comment by gati** [comment]
Good points on both! This process is pretty ad hoc right now. We should definitely include a message to organizations who need help, and a way for them to contact us. I think we could *probably* take a more automated approach to Slack invites, but I kind of like having a human filter, even if it's 10 seconds of scanning someone's message, before sending the invite (as opposed to people being able to anonymously invite themselves)
