### ISSUE TITLE
Projects page copy

### ISSUE THREAD

**Issue by gati** [Data4Democracy/datafordemocracy.org#13]
- What kind of projects we look for
- Explain that we have community-led and partner-led
- What it likes to work on a D4D project - (random idea: maybe a community member knows a little video production, and we could get people to record 10-30 second testimonials and we could explain this with a video?) 
- Teaser paragraph about each active project, include title, elevator pitch, name(s) of project lead(s), link to public Github repo (if available), public data.world dataset (if available), or public application (if available)

**Comment by ehbick01** [comment]
@gati happy to work on this as well!

**Comment by gati** [comment]
@ehbick01 that's cool with me, but going to hold off on assigning if that's cool, because I know Lillian wanted to pick up some of the copy as well and I don't think she's on GitHub yet

**Comment by ehbick01** [comment]
Of course! Teamwork makes the dream work!

**Comment by gati** [comment]
So true

**Comment by lilianhj** [comment]
I can work on this, if that's okay with you all! :)

**Comment by gati** [comment]
@lilianhj go for it!

**Comment by lilianhj** [comment]
Drafted the copy! Sorry if I fumbled the commit process - I'm pretty new to Github.

**Comment by gati** [comment]
@lilianhj this looks awesome! I just realized we've been using everyone's Slack handle everywhere, which is helpful for people joining the Slack, but occurred to me the project leads might want to use their real names and link to the social media/LinkedIn/whatever on the public site. I've asked the project leads to leave their name and whatever social media links they'd like to use as comments on the issue. :) 

Thanks for diving into Github! Process was perfect (impressive that it went so well the first time!) - as we get closer to being finished, we'll probably do "pull requests" (aka PRs). Now that you've gone through the normal commit process you should be fine - I'll DM some instructions for how those work!

**Comment by ehbick01** [comment]
Eric Bickel
Twitter: eric_bickel
Github: ehbick01

**Comment by ehbick01** [comment]
Co-leading Propublica!

**Comment by jenniferthompson** [comment]
Jennifer Thompson
Twitter: @jent103
Github/data.world: @jenniferthompson
Co-leading drug-spending

**Comment by sjacks26** [comment]
Sam Jackson
Twitter: sjacks26
Co-leading far-right (Not sure if we're putting this one one the website, but in case we are!)

**Comment by scottcame** [comment]
Scott Came
Twitter: @scottcame
GitHub/data.world/dockerhub: scottcame
LinkedIn:  www.linkedin.com/in/scottcame

Co-leading election-transparency

**Comment by wwymak** [comment]
Wendy Mak
twitter/ GitHub: wwymak
co-leading nlp-twitter (building / exploring nlp pipelines and methods for analysing twitter textual data-- possibly also from other social media in the future)

**Comment by mattgawarecki** [comment]
Matt Gawarecki
Twitter/GitHub: @mattgawarecki
LinkedIn: https://linkedin.com/in/mattgawarecki

Co-leading drug-spending (researching trends in Medicare drug spending to identify patterns, reduce costs, and increase awareness)

**Comment by restrellado** [comment]
Ryan Estrellado
Twitter: @RyanEs 
GitHub: restrellado
Co-leading ProPublica

**Comment by hadoopjax** [comment]
Totally not sure if we're ok with this format but here's what I can do:

Nick
Twitter: @hadoopjax
GitHub: @hadoopjax
Co-leading assemble, far-right, discursive, collect-social

Happy to be on the hook for helping draft a blurb for each with the other co-leads

**Comment by rachelanddata** [comment]
Rachel Rinaldi
Twitter: rachelanddata
Co-lead for election-transparency

**Comment by bstarling** [comment]
Benjamin Starling
Twitter: [@bstarling_](https://twitter.com/bstarling_)
Github: [bstarling](https://github.com/bstarling)
Co-Lead : Assemble

**Comment by chrisdick14** [comment]
Chris Dick
Twitter: @chris_dick
GitHub/data.world: @chrisdick14

Co-leading election-transparency and womens-march

**Comment by gati** [comment]
Closing this issue, will refer to it for individual project pages, where leads are listed.
