### ISSUE TITLE
Add blog, join us, and partner links to main navigation

### ISSUE THREAD

**Issue by gati** [Data4Democracy/datafordemocracy.org#21]

**Comment by geckya** [comment]
I could do the join us and partner links, but the blog link is actually commented out from the main nav bar right because it wasn't working the way I expected - once someone fixes this, I'd love to know how/why it wasn't working for me!

**Comment by gati** [comment]
Aha. Weird. OK I'll take a look at the blog link and see what's up

**Comment by gati** [comment]
Closing, nav got updated when we changed themes.
