### ISSUE TITLE
Add a separate page just for partners

### ISSUE THREAD

**Issue by gati** [Data4Democracy/datafordemocracy.org#22]

**Comment by geckya** [comment]
Tech partners, or project partners (eg, City of Boston and ProPublica)? There should be a bare bones tech_partners page already.

**Comment by gati** [comment]
Oh cool! Sorry I missed that. I was thinking one page for both. I thought it was cool that you called out Boston and ProPublica. Figured we could build on that :)

**Comment by gati** [comment]
Oh cool! Sorry I missed that. I was thinking one page for both. I thought it was cool that you called out Boston and ProPublica. Figured we could build on that :)

**Comment by geckya** [comment]
So, just move `tech_partners` to `partners`?
