### ISSUE TITLE
Partner page copy

### ISSUE THREAD

**Issue by gati** [Data4Democracy/datafordemocracy.org#24]
- Explain that we partner with cities, non-profits, and other institutions working for the public good
- We also partner with technology companies who want their products and platforms to support the work our volunteers are doing
- List each partner, with a paragraph explaining our relationship with each. For example: "We partner with Domino Data Labs to use their innovative platform for collaborative research and analysis." <--- that is a horrible sentence, I'm just including it for tone. :)

**Comment by ehbick01** [comment]
@gati I'm happy to tackle the copy on this!

**Comment by gati** [comment]
@ehbick01 go for it!
