### ISSUE TITLE
What we can do copy/image

### ISSUE THREAD

**Issue by gati** [Data4Democracy/datafordemocracy.org#28]
The "WHAT WE CAN DO" section on the homepage should describe the capabilities of the community. We do data engineering, machine learning, analysis, software engineering, community management, and are awesome!

We should probably flush that out a little bit, maybe include the notion of who we're using the skills to support - people who want to participate, making our communities more resilient and inclusive, all that stuff.

**Comment by geckya** [comment]
I slotted some stuff in, but it could definitely stand to be improved.

**Comment by numadhamani** [comment]
Picking this up!
