### ISSUE TITLE
The Numbers copy/image

### ISSUE THREAD

**Issue by gati** [Data4Democracy/datafordemocracy.org#29]
- update to use accurate numbers from the community (number of volunteers, github repos, active projects, messages in slack, whatever sounds cool to you)
- the section of copy here is probably a good place to talk about how quickly we're growing, and why we think it's important to be a gathering place for everyone who wants to use their tech powers for good. 
- find a background image for this section (maybe by searching Flickr creative commons)

**Comment by numadhamani** [comment]
Picking this up!
