### ISSUE TITLE
Our "customers" copy/image

### ISSUE THREAD

**Issue by gati** [Data4Democracy/datafordemocracy.org#30]
we should change this to our "partners" and use logos from Domino, data.world, Eventador, Mode, City of Boston, City of LA, City of San Diego. 

The copy could reference that, while some projects are community driven, we also partner with organizations to support their missions.

Last but not least, find a background image for this section, maybe using Flickr creative commons.

**Comment by lilianhj** [comment]
I can take this on, if that's okay.

**Comment by gati** [comment]
Go for it! Thanks for grabbing this :)

**Comment by ehbick01** [comment]
You definitely don't have to use it - but the 'partners' copy I think is saved somewhere in the repo still. Doesn't have logos, though

**Comment by geckya** [comment]
I did grab what @ehbick01 did the other day - it's at https://data4democracy.github.io/datafordemocracy.org/partners.html - the link to it from the home page appears to be broken, though.

**Comment by geckya** [comment]
This issue overlaps with issues 22, 23, and 24.
