### ISSUE TITLE
Homepage layout changes

### ISSUE THREAD

**Issue by gati** [Data4Democracy/datafordemocracy.org#31]
Remove "our team" and "like what you see here?" section on the homepage.

Re: Our Team - I'm open to a discussion about this, but I'm not really sure who we would/wouldn't list here. The community is too big to list all 650 people, but there's no sub group (like staff or something) that makes sense in this space, so IMHO we should just remove it. But! Comment if you disagree :)

**Comment by geckya** [comment]
I think we pull "Our Team" for now. Down the road, we can add it back in - maybe as a rotating "spotlight" of selected contributors, or the people who sit on the board I imagine we'll probably have to have once/if we incorporate and go 501c(3).
