### ISSUE TITLE
nav bar rendering strangely

### ISSUE THREAD

**Issue by geckya** [Data4Democracy/datafordemocracy.org#37]
No longer up at the top, and some orphaned curly braces are under the labels.

**Comment by geckya** [comment]
Looks like we have two different issues - the curly braces have been around for a while.  The extra spacing seems to be a result of changing the logo - the new, unpixellated text version is larger than the old one, so I'm nominating @cheapwebmonkey to fix that.  If you can't, let me know and I'll try to get it done tomorrow!

**Comment by cheapwebmonkey** [comment]
I am not seeing any curly braces

**Comment by cheapwebmonkey** [comment]
PR open for logo fix

**Comment by geckya** [comment]
I'll post some screen grabs in a bit - I'm AFK right now. The change in the PR did change the logo size, but didn't fix the problem, and appears to have introduced a new one.

**Comment by cheapwebmonkey** [comment]
ummm- all i did was decrease it to 20%, literally all I changed

**Comment by geckya** [comment]
Found the rogue curly braces - will include fix in my next push.
